package net.jelly.marionette_lib.entity.examples.tentacle;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.math.Axis;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.renderer.culling.Frustum;
import net.minecraft.client.renderer.entity.EntityRendererProvider;
import net.minecraft.client.renderer.entity.MobRenderer;
import net.minecraft.resources.ResourceLocation;

/**
 * Generated by the Marionette Blockbench plugin. Regenerating overwrites this
 * file -- keep hand edits somewhere else.
 *
 * Two registrations are still yours to make, because they live in your mod's
 * event classes rather than here:
 *
 *   EntityRenderersEvent.RegisterLayerDefinitions:
 *       event.registerLayerDefinition(TentacleRenderer.TENTACLE_LAYER, TentacleModel::createBodyLayer);
 *
 *   EntityRenderersEvent.RegisterRenderers:
 *       event.registerEntityRenderer(ModEntities.TENTACLE.get(), TentacleRenderer::new);
 */
public class TentacleRenderer extends MobRenderer<TentacleEntity, TentacleModel> {

    private static final ResourceLocation TEXTURE =
            new ResourceLocation("marionette_lib:textures/entity/tentacle.png");

    public static final ModelLayerLocation TENTACLE_LAYER = new ModelLayerLocation(
            new ResourceLocation("marionette_lib", "tentacle_layer"), "main");

    public TentacleRenderer(EntityRendererProvider.Context context) {
        super(context, new TentacleModel(context.bakeLayer(TENTACLE_LAYER)), 0.5F);
    }

    @Override
    protected void setupRotations(TentacleEntity entity, PoseStack poseStack, float ageInTicks, float rotationYaw, float partialTicks) {
        // Segment positions are already world-space, so the entity's own yaw must
        // not be applied on top. The 180 turn matches Blockbench's +Z forward.
        poseStack.mulPose(Axis.YP.rotationDegrees(180));
    }

    @Override
    public boolean shouldRender(TentacleEntity entity, Frustum camera, double x, double y, double z) {
        // A limb can reach far outside the entity's own box; without this the
        // whole model pops out of view when the root leaves the frustum.
        if (super.shouldRender(entity, camera, x, y, z)) return true;
        return camera.isVisible(entity.getMarionetteBoundingBoxForCulling(entity));
    }

    @Override
    public ResourceLocation getTextureLocation(TentacleEntity entity) {
        return TEXTURE;
    }
}
