package net.jelly.marionette_lib.entity.examples.tentacle;

import net.jelly.marionette_lib.utility.MarionetteModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;

/**
 * Generated by the Marionette Blockbench plugin. Regenerating overwrites this
 * file -- keep hand edits somewhere else.
 *
 * Segment names below are in chain order and are index-aligned with
 * TentacleEntity's part list. Reordering one without the other will
 * silently pair the wrong model part with the wrong segment.
 */
public class TentacleModel extends MarionetteModel<TentacleEntity> {

    public static LayerDefinition createBodyLayer() {
        MeshDefinition meshdefinition = new MeshDefinition();
        PartDefinition partdefinition = meshdefinition.getRoot();

        PartDefinition segment = partdefinition.addOrReplaceChild("segment", CubeListBuilder.create(), PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition geo = segment.addOrReplaceChild("geo", CubeListBuilder.create()
                .texOffs(0, 0).addBox(-2.0F, -2.0F, -1.0F, 4.0F, 4.0F, 9.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.0F, -4.0F));

        PartDefinition segment2 = partdefinition.addOrReplaceChild("segment2", CubeListBuilder.create()
                .texOffs(0, 13).addBox(-1.0F, -1.0F, -5.0F, 2.0F, 2.0F, 9.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition segment3 = partdefinition.addOrReplaceChild("segment3", CubeListBuilder.create()
                .texOffs(22, 13).addBox(-1.0F, -1.0F, -5.0F, 2.0F, 2.0F, 9.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition segment2_bone = segment3.addOrReplaceChild("segment2_bone", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, -12.0F, -1.5708F, 0.0F, 0.0F));

        PartDefinition segment4 = partdefinition.addOrReplaceChild("segment4", CubeListBuilder.create()
                .texOffs(0, 24).addBox(-1.0F, -1.0F, -5.0F, 2.0F, 2.0F, 9.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition segment2_bone2 = segment4.addOrReplaceChild("segment2_bone2", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, -12.0F, -1.5708F, 0.0F, 0.0F));

        PartDefinition segment3_bone = segment4.addOrReplaceChild("segment3_bone", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, -21.0F, -1.5708F, 0.0F, 0.0F));

        PartDefinition segment5 = partdefinition.addOrReplaceChild("segment5", CubeListBuilder.create()
                .texOffs(22, 24).addBox(-1.0F, -1.0F, -5.0F, 2.0F, 2.0F, 9.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition segment2_bone3 = segment5.addOrReplaceChild("segment2_bone3", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, -12.0F, -1.5708F, 0.0F, 0.0F));

        PartDefinition segment3_bone2 = segment5.addOrReplaceChild("segment3_bone2", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, -21.0F, -1.5708F, 0.0F, 0.0F));

        return LayerDefinition.create(meshdefinition, 64, 64);
    }

    public TentacleModel(ModelPart root) {
        super(root, new String[] {
            "segment", "segment2", "segment3", "segment4", "segment5"
        });
    }
}
