package net.jelly.marionette_lib.entity.examples.tentacle;

import net.jelly.marionette_lib.utility.Limb;
import net.jelly.marionette_lib.utility.Marionette;
import net.jelly.marionette_lib.utility.MarionettePart;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.Mob;
import net.minecraft.world.entity.ai.attributes.AttributeSupplier;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.entity.animal.Animal;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.level.Level;
import net.minecraftforge.entity.PartEntity;

import java.util.List;

/**
 * Generated by the Marionette Blockbench plugin. Regenerating overwrites this
 * file -- keep hand edits somewhere else.
 *
 * The segment dimensions below came from the Blockbench geometry:
 * {@code length} is the bone length in blocks and is exact; {@code sizeXZ} and
 * {@code sizeY} are hitbox sizes derived from each segment's bounding box, which
 * Blockbench has no way to express, so tune them.
 *
 * Limb order here defines part order, which TentacleModel's segment
 * name array must match.
 */
public class TentacleEntity extends Mob implements Marionette {

    private final Limb<MarionettePart<TentacleEntity>> limb;

    public TentacleEntity(EntityType<? extends Mob> entityType, Level level) {
        super(entityType, level);
        limb = Limb.builder(this)
                .segment(0.25F, 0.25F, 0.5F)
                .segments(4, 0.125F, 0.125F, 0.5F)
                .build();
    }

    public static AttributeSupplier.Builder createAttributes() {
        return Animal.createLivingAttributes()
                .add(Attributes.MAX_HEALTH, 20D)
                .add(Attributes.FOLLOW_RANGE, 24D)
                .add(Attributes.MOVEMENT_SPEED, 0.25D)
                .add(Attributes.ARMOR_TOUGHNESS, 0.1f)
                .add(Attributes.ATTACK_KNOCKBACK, 0.5f)
                .add(Attributes.ATTACK_DAMAGE, 2f);
    }

    @Override
    public List<Limb<?>> getLimbs() {
        return List.of(limb);
    }

    // Forge's Entity defines concrete versions of the next three, which win over
    // the interface defaults, so they have to be forwarded by hand.

    @Override
    public boolean isMultipartEntity() {
        return true;
    }

    @Override
    public PartEntity<?>[] getParts() {
        return getMarionetteParts();
    }

    @Override
    public void remove(RemovalReason removalReason) {
        super.remove(removalReason);
        removeMarionette(removalReason);
    }

    @Override
    public void tick() {
        super.tick();

        // Aim each limb before solving, e.g.
        //     limb.animator().setFabrikTarget(someWorldPosition);
        Player nearestPlayer = this.level().getNearestPlayer(this, 200);
        if (nearestPlayer != null) limb.animator().setFabrikTarget(nearestPlayer.position());

        tickMarionette();
    }
}
