package net.jelly.marionette_lib.entity.examples.testwyvern;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.math.Axis;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.renderer.culling.Frustum;
import net.minecraft.client.renderer.entity.EntityRendererProvider;
import net.minecraft.client.renderer.entity.MobRenderer;
import net.minecraft.resources.ResourceLocation;

/**
 * Generated by the Marionette Blockbench plugin. Regenerating overwrites this
 * file. Keep hand edits elsewhere.
 *
 * Like a vanilla modded entity, wo registrations are still yours to make:
 *
 *   EntityRenderersEvent.RegisterLayerDefinitions:
 *       event.registerLayerDefinition(TestWyvernRenderer.TEST_WYVERN_LAYER, TestWyvernModel::createBodyLayer);
 *
 *   EntityRenderersEvent.RegisterRenderers:
 *       event.registerEntityRenderer(ModEntities.TEST_WYVERN.get(), TestWyvernRenderer::new);
 */
public class TestWyvernRenderer extends MobRenderer<TestWyvernEntity, TestWyvernModel> {

    private static final ResourceLocation TEXTURE =
            new ResourceLocation("marionette_lib:textures/entity/test_wyvern.png");

    public static final ModelLayerLocation TEST_WYVERN_LAYER = new ModelLayerLocation(
            new ResourceLocation("marionette_lib", "test_wyvern_layer"), "main");

    public TestWyvernRenderer(EntityRendererProvider.Context context) {
        super(context, new TestWyvernModel(context.bakeLayer(TEST_WYVERN_LAYER)), 0.5F);
    }

    @Override
    protected void setupRotations(TestWyvernEntity entity, PoseStack poseStack, float ageInTicks, float rotationYaw, float partialTicks) {
        poseStack.mulPose(Axis.YP.rotationDegrees(180));
    }

    @Override
    public boolean shouldRender(TestWyvernEntity entity, Frustum camera, double x, double y, double z) {
        if (super.shouldRender(entity, camera, x, y, z)) return true;
        return camera.isVisible(entity.getMarionetteBoundingBoxForCulling(entity));
    }

    @Override
    public ResourceLocation getTextureLocation(TestWyvernEntity entity) {
        return TEXTURE;
    }
}
