package net.jelly.marionette_lib.entity.examples.testwyvern;

import net.jelly.marionette_lib.utility.Limb;
import net.jelly.marionette_lib.utility.MarionettePart;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.phys.Vec3;

import java.util.List;

/**
 * Generated by the Marionette Blockbench plugin. Regenerating overwrites this
 * file, and only this file: the entity class alongside it is yours.
 *
 * The segment dimensions below came from the Blockbench geometry:
 * {@code length} is the bone length in blocks and is exact; {@code sizeXZ} and
 * {@code sizeY} are hitbox sizes guessed from each segment's bounding box, which
 * will likely require tuning.
 *
 * Generic on the owner so this file never names the entity class. Instantiate
 * it as {@code new TestWyvernRig<>(this)}; the limb types come out fully concrete.
 */
public class TestWyvernRig<E extends Entity> {

    public final Limb<MarionettePart<E>> limb;
    public final Limb<MarionettePart<E>> limb2;
    public final Limb<MarionettePart<E>> limb3;
    public final Limb<MarionettePart<E>> limb4;
    public final Limb<MarionettePart<E>> limb5;

    public TestWyvernRig(E owner) {
        limb = Limb.builder(owner)
                .segment(0.25F, 0.25F, 0.5F)
                .segments(4, 0.125F, 0.125F, 0.5F)
                .followRootOnly(true)
                .build();

        limb2 = Limb.builder(owner)
                .segments(3, 0.125F, 0.125F, 0.5F)
                .rootPrimeDirection(new Vec3(0.442511, 0.725928, 0.52651))
                .attachRoot(limb.parts()[2], new Vec3(0.032551, 0.004311, -0.178872))
                .build();

        limb3 = Limb.builder(owner)
                .segments(3, 0.125F, 0.125F, 0.5F)
                .rootPrimeDirection(new Vec3(-0.480269, 0.736601, 0.476195))
                .attachRoot(limb.parts()[2], new Vec3(-0.042449, 0.004311, -0.178872))
                .build();

        limb4 = Limb.builder(owner)
                .segments(3, 0.125F, 0.125F, 0.5F)
                .rootPrimeDirection(new Vec3(0.638664, 0.658547, -0.398024))
                .attachRoot(limb.parts()[4], new Vec3(0.032551, 0.004311, -0.178872))
                .build();

        limb5 = Limb.builder(owner)
                .segments(3, 0.125F, 0.125F, 0.5F)
                .rootPrimeDirection(new Vec3(-0.609997, 0.627631, -0.483718))
                .attachRoot(limb.parts()[4], new Vec3(-0.042449, 0.004311, -0.178872))
                .build();
    }

    /**
     * Declaration order is part order, which the segment name array in
     * TestWyvernModel must match. Return this from the entity's {@code getLimbs()}.
     */
    public List<Limb<?>> limbs() {
        return List.of(limb, limb2, limb3, limb4, limb5);
    }
}
