package net.jelly.marionette_lib.entity.examples.testwyvern;

import net.jelly.marionette_lib.utility.FabrikAnimator;
import net.jelly.marionette_lib.utility.Limb;
import net.jelly.marionette_lib.utility.Marionette;
import net.jelly.marionette_lib.utility.MarionettePart;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.ai.attributes.AttributeSupplier;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.entity.animal.Animal;
import net.minecraft.world.entity.monster.Phantom;
import net.minecraft.world.level.Level;
import net.minecraft.world.phys.Vec3;
import net.minecraftforge.entity.PartEntity;

import java.util.List;

/**
 * Generated by the Marionette Blockbench plugin. Regenerating overwrites this
 * file. Keep hand edits elsewhere.
 *
 * The segment dimensions below came from the Blockbench geometry:
 * {@code length} is the bone length in blocks and is exact; {@code sizeXZ} and
 * {@code sizeY} are hitbox sizes guessed from each segment's bounding box, which
 * will likely require tuning.
 *
 * Limb order defines part order, which TestWyvernModel's segment
 * name array must match.
 */
public class TestWyvernEntity extends Phantom implements Marionette {
    private static final int LEG_COUNT = 4;

    // wyvern's step shape held in proportion: a leg here is three 0.5 block segments, 1.5 blocks of
    // reach against the wyvern's 2, so its rest spot and thresholds scale with that
    private static final float LEG_REACH = 1.5f;
    private static final float REST_SIDEWAYS = 0.75f * LEG_REACH;
    private static final float REST_FORWARD = 0.625f * LEG_REACH;
    private static final float STEP_DISTANCE = LEG_REACH;
    private static final float SETTLE_DISTANCE = 0.3f * LEG_REACH;

    private final Limb<MarionettePart<TestWyvernEntity>> limb;
    private final Limb<MarionettePart<TestWyvernEntity>> limb2;
    private final Limb<MarionettePart<TestWyvernEntity>> limb3;
    private final Limb<MarionettePart<TestWyvernEntity>> limb4;
    private final Limb<MarionettePart<TestWyvernEntity>> limb5;

    private final List<Limb<MarionettePart<TestWyvernEntity>>> legs;
    private final boolean[] legReturning = new boolean[LEG_COUNT];

    public TestWyvernEntity(EntityType<? extends Phantom> entityType, Level level) {
        super(entityType, level);
        limb = Limb.builder(this)
                .segment(0.25F, 0.25F, 0.5F)
                .segments(4, 0.125F, 0.125F, 0.5F)
                .followRootOnly(true)
                .build();

        limb2 = Limb.builder(this)
                .segments(3, 0.125F, 0.125F, 0.5F)
                .rootPrimeDirection(new Vec3(0.442511, 0.725928, 0.52651))
                .attachRoot(limb.parts()[2], new Vec3(0.032551, 0.004311, -0.178872))
                .build();

        limb3 = Limb.builder(this)
                .segments(3, 0.125F, 0.125F, 0.5F)
                .rootPrimeDirection(new Vec3(-0.480269, 0.736601, 0.476195))
                .attachRoot(limb.parts()[2], new Vec3(-0.042449, 0.004311, -0.178872))
                .build();

        limb4 = Limb.builder(this)
                .segments(3, 0.125F, 0.125F, 0.5F)
                .rootPrimeDirection(new Vec3(0.638664, 0.658547, -0.398024))
                .attachRoot(limb.parts()[4], new Vec3(0.032551, 0.004311, -0.178872))
                .build();

        limb5 = Limb.builder(this)
                .segments(3, 0.125F, 0.125F, 0.5F)
                .rootPrimeDirection(new Vec3(-0.609997, 0.627631, -0.483718))
                .attachRoot(limb.parts()[4], new Vec3(-0.042449, 0.004311, -0.178872))
                .build();

        legs = List.of(limb2, limb3, limb4, limb5);
    }

    @Override
    public List<Limb<?>> getLimbs() {
        return List.of(limb, limb2, limb3, limb4, limb5);
    }

    @Override
    public boolean isMultipartEntity() {
        return true;
    }

    @Override
    public PartEntity<?>[] getParts() {
        return getMarionetteParts();
    }

    @Override
    public void remove(RemovalReason removalReason) {
        super.remove(removalReason);
        removeMarionette(removalReason);
    }

    @Override
    public void tick() {
        super.tick();

        for (int i = 0; i < LEG_COUNT; i++) {
            stepLeg(i);
        }

        tickMarionette();
    }

    /** Keeps leg {@code i}'s foot near its resting spot relative to the body, stepping when it drifts too far. */
    private void stepLeg(int i) {
        FabrikAnimator legAnimator = legs.get(i).animator();
        // the pair index the exported limb attached itself to, which is where its root already resolves
        int rootIndex = i <= 1 ? 2 : 4;
        MarionettePart<TestWyvernEntity> rootPart = limb.parts()[rootIndex];
        int bodySide = i % 2 == 0 ? 1 : -1;

        Vec3 direction = limb.parts()[rootIndex - 1].position().subtract(rootPart.position()).normalize();
        Vec3 legRest = rootPart.position()
                .add(direction.cross(new Vec3(0, 1, 0)).normalize().scale(REST_SIDEWAYS * bodySide))
                .add(direction.scale(REST_FORWARD));

        if (legAnimator.chainEndPos().distanceTo(legRest) > STEP_DISTANCE) {
            legReturning[i] = true;
        }

        if (legReturning[i]) {
            legAnimator.setFabrikTarget(legAnimator.chainEndPos()
                    .add(legRest.subtract(legAnimator.chainEndPos()).normalize()
                            .scale(this.getDeltaMovement().dot(legRest.subtract(legAnimator.chainEndPos()))))
                    .add(legRest.subtract(legAnimator.chainEndPos()).scale(0.25))
                    .add(legRest.subtract(legAnimator.chainEndPos()).normalize().scale(0.1))
            );
            if (legAnimator.chainEndPos().distanceTo(legRest) < SETTLE_DISTANCE) {
                legReturning[i] = false;
            }
        }
    }

    public static AttributeSupplier.Builder createAttributes() {
        return Animal.createLivingAttributes()
                .add(Attributes.MAX_HEALTH, 20D)
                .add(Attributes.FOLLOW_RANGE, 24D)
                .add(Attributes.MOVEMENT_SPEED, 0.25D)
                .add(Attributes.ARMOR_TOUGHNESS, 0.1f)
                .add(Attributes.ATTACK_KNOCKBACK, 0.5f)
                .add(Attributes.ATTACK_DAMAGE, 2f);
    }

    @Override
    protected boolean isSunBurnTick() {
        return false;
    }
}
