package net.jelly.marionette_lib.entity.examples.testwyvern;

import net.jelly.marionette_lib.utility.MarionetteModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;

/**
 * Generated by the Marionette Blockbench plugin. Regenerating overwrites this
 * file -- keep hand edits somewhere else.
 *
 * Segment names below are in chain order and are index-aligned with
 * TestWyvernEntity's part list. Reordering one without the other will
 * silently pair the wrong model part with the wrong segment.
 */
public class TestWyvernModel extends MarionetteModel<TestWyvernEntity> {

    public static LayerDefinition createBodyLayer() {
        MeshDefinition meshdefinition = new MeshDefinition();
        PartDefinition partdefinition = meshdefinition.getRoot();

        PartDefinition segment = partdefinition.addOrReplaceChild("segment", CubeListBuilder.create(), PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition geo = segment.addOrReplaceChild("geo", CubeListBuilder.create()
                .texOffs(0, 0).addBox(-2.0F, -2.0F, -1.0F, 4.0F, 4.0F, 9.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.0F, -4.0F));

        PartDefinition segment3 = partdefinition.addOrReplaceChild("segment3", CubeListBuilder.create()
                .texOffs(0, 13).addBox(-1.0F, -1.0F, -5.0F, 2.0F, 2.0F, 9.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition segment2_bone = segment3.addOrReplaceChild("segment2_bone", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, -12.0F, -1.5708F, 0.0F, 0.0F));

        PartDefinition segment4 = partdefinition.addOrReplaceChild("segment4", CubeListBuilder.create()
                .texOffs(22, 13).addBox(-1.0F, -1.0F, -5.0F, 2.0F, 2.0F, 9.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition segment2_bone2 = segment4.addOrReplaceChild("segment2_bone2", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, -12.0F, -1.5708F, 0.0F, 0.0F));

        PartDefinition segment3_bone = segment4.addOrReplaceChild("segment3_bone", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, -21.0F, -1.5708F, 0.0F, 0.0F));

        PartDefinition segment5 = partdefinition.addOrReplaceChild("segment5", CubeListBuilder.create()
                .texOffs(0, 24).addBox(-1.0F, -1.0F, -5.0F, 2.0F, 2.0F, 9.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition segment2_bone3 = segment5.addOrReplaceChild("segment2_bone3", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, -12.0F, -1.5708F, 0.0F, 0.0F));

        PartDefinition segment3_bone2 = segment5.addOrReplaceChild("segment3_bone2", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, -21.0F, -1.5708F, 0.0F, 0.0F));

        PartDefinition segment2 = partdefinition.addOrReplaceChild("segment2", CubeListBuilder.create()
                .texOffs(22, 24).addBox(-1.0F, -1.0F, -5.0F, 2.0F, 2.0F, 9.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition segment2_bone4 = segment2.addOrReplaceChild("segment2_bone4", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, -12.0F, -1.5708F, 0.0F, 0.0F));

        PartDefinition segment3_bone3 = segment2.addOrReplaceChild("segment3_bone3", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, -21.0F, -1.5708F, 0.0F, 0.0F));

        PartDefinition segment4_bone = segment2.addOrReplaceChild("segment4_bone", CubeListBuilder.create(), PartPose.offsetAndRotation(0.0F, 0.0F, -30.0F, -1.5708F, 0.0F, 0.0F));

        PartDefinition segment6 = partdefinition.addOrReplaceChild("segment6", CubeListBuilder.create()
                .texOffs(26, 0).addBox(-1.0F, -1.0F, -4.0F, 2.0F, 2.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition segment7 = partdefinition.addOrReplaceChild("segment7", CubeListBuilder.create()
                .texOffs(0, 35).addBox(-1.0F, -1.0F, -4.0F, 2.0F, 2.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition segment8 = partdefinition.addOrReplaceChild("segment8", CubeListBuilder.create()
                .texOffs(20, 35).addBox(-1.0F, -1.0F, -4.0F, 2.0F, 2.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition segment9 = partdefinition.addOrReplaceChild("segment9", CubeListBuilder.create()
                .texOffs(44, 20).addBox(-1.0F, -1.0F, -4.0F, 2.0F, 2.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition segment6_bone = segment9.addOrReplaceChild("segment6_bone", CubeListBuilder.create(), PartPose.offsetAndRotation(0.3208F, 0.069F, -31.138F, -1.5708F, 0.0F, 0.0F));

        PartDefinition segment10 = partdefinition.addOrReplaceChild("segment10", CubeListBuilder.create()
                .texOffs(40, 35).addBox(-1.0F, -1.0F, -4.0F, 2.0F, 2.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition segment7_bone = segment10.addOrReplaceChild("segment7_bone", CubeListBuilder.create(), PartPose.offsetAndRotation(0.3208F, 0.069F, -39.138F, -1.5708F, 0.0F, 0.0F));

        PartDefinition segment11 = partdefinition.addOrReplaceChild("segment11", CubeListBuilder.create()
                .texOffs(44, 10).addBox(-1.0F, -1.0F, -4.0F, 2.0F, 2.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition segment8_bone = segment11.addOrReplaceChild("segment8_bone", CubeListBuilder.create(), PartPose.offsetAndRotation(0.3208F, 0.069F, -39.138F, -1.5708F, 0.0F, 0.0F));

        PartDefinition segment12 = partdefinition.addOrReplaceChild("segment12", CubeListBuilder.create()
                .texOffs(40, 45).addBox(-1.0F, -1.0F, -4.0F, 2.0F, 2.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition segment6_bone2 = segment12.addOrReplaceChild("segment6_bone2", CubeListBuilder.create(), PartPose.offsetAndRotation(0.5208F, 0.069F, -31.138F, -1.5708F, 0.0F, 0.0F));

        PartDefinition segment13 = partdefinition.addOrReplaceChild("segment13", CubeListBuilder.create()
                .texOffs(0, 45).addBox(-1.0F, -1.0F, -4.0F, 2.0F, 2.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition segment7_bone2 = segment13.addOrReplaceChild("segment7_bone2", CubeListBuilder.create(), PartPose.offsetAndRotation(0.5208F, 0.069F, -39.138F, -1.5708F, 0.0F, 0.0F));

        PartDefinition segment14 = partdefinition.addOrReplaceChild("segment14", CubeListBuilder.create()
                .texOffs(20, 45).addBox(-1.0F, -1.0F, -4.0F, 2.0F, 2.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition segment8_bone2 = segment14.addOrReplaceChild("segment8_bone2", CubeListBuilder.create(), PartPose.offsetAndRotation(0.5208F, 0.069F, -39.138F, -1.5708F, 0.0F, 0.0F));

        PartDefinition segment15 = partdefinition.addOrReplaceChild("segment15", CubeListBuilder.create()
                .texOffs(20, 55).addBox(-1.0F, -1.0F, -4.0F, 2.0F, 2.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition segment6_bone3 = segment15.addOrReplaceChild("segment6_bone3", CubeListBuilder.create(), PartPose.offsetAndRotation(0.3208F, 0.069F, -31.138F, -1.5708F, 0.0F, 0.0F));

        PartDefinition segment9_bone = segment15.addOrReplaceChild("segment9_bone", CubeListBuilder.create(), PartPose.offsetAndRotation(-0.6792F, 0.069F, -31.138F, -1.5708F, 0.0F, 0.0F));

        PartDefinition segment16 = partdefinition.addOrReplaceChild("segment16", CubeListBuilder.create()
                .texOffs(46, 0).addBox(-1.0F, -1.0F, -4.0F, 2.0F, 2.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition segment7_bone3 = segment16.addOrReplaceChild("segment7_bone3", CubeListBuilder.create(), PartPose.offsetAndRotation(0.3208F, 0.069F, -39.138F, -1.5708F, 0.0F, 0.0F));

        PartDefinition segment10_bone = segment16.addOrReplaceChild("segment10_bone", CubeListBuilder.create(), PartPose.offsetAndRotation(-0.6792F, 0.069F, -39.138F, -1.5708F, 0.0F, 0.0F));

        PartDefinition segment17 = partdefinition.addOrReplaceChild("segment17", CubeListBuilder.create()
                .texOffs(0, 55).addBox(-1.0F, -1.0F, -4.0F, 2.0F, 2.0F, 8.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 24.0F, 0.0F));

        PartDefinition segment8_bone3 = segment17.addOrReplaceChild("segment8_bone3", CubeListBuilder.create(), PartPose.offsetAndRotation(0.3208F, 0.069F, -39.138F, -1.5708F, 0.0F, 0.0F));

        PartDefinition segment11_bone = segment17.addOrReplaceChild("segment11_bone", CubeListBuilder.create(), PartPose.offsetAndRotation(-0.6792F, 0.069F, -39.138F, -1.5708F, 0.0F, 0.0F));

        return LayerDefinition.create(meshdefinition, 128, 128);
    }

    public TestWyvernModel(ModelPart root) {
        super(root, new String[] {
            "segment", "segment3", "segment4", "segment5", "segment2", "segment6", "segment7",
            "segment8", "segment9", "segment10", "segment11", "segment12", "segment13", "segment14",
            "segment15", "segment16", "segment17"
        });
    }
}
