// java emitters: rig.js's plain rig description in, source strings out
// no blockbench globals for golden testing
// coordinate conventions are the Modded Entity codec's, reproduced from modded_entity.js with flip_y true
// later we might want to have flip_y false, removing the unflipping work in the renderer, but this is safer for now
// the only substitution is everywhere the codec would use group.origin, this uses the segment's export origin (the bone's center)
// that's kinda the entire point of the plugin, the centering the user used to do by hand

const RAD = Math.PI / 180;

// java float literal matching codec's formatting (-4.0F, 0.3927F)
export function f(value) {
	const n = Object.is(value, -0) ? 0 : value;
	if (Number.isInteger(n)) return `${n.toFixed(1)}F`;
	return `${parseFloat(n.toFixed(4))}F`;
}

function rad(degrees) {
	return f(degrees * RAD);
}

// Vec3 takes doubles, not floats
function d(value) {
	const n = Object.is(value, -0) ? 0 : value;
	return Number.isInteger(n) ? n.toFixed(1) : String(parseFloat(n.toFixed(6)));
}

// verbatim from the codec
export function cubeOffset(cube, origin) {
	return [
		origin[0] - cube.to[0],
		-cube.from[1] - cube.size[1] + origin[1],
		cube.from[2] - origin[2],
	];
}

// no +24 offset here, thats root only
export function childPose(part, parentOrigin) {
	const offset = [
		-(part.origin[0] - parentOrigin[0]),
		-(part.origin[1] - parentOrigin[1]),
		part.origin[2] - parentOrigin[2],
	];

	const [rx, ry, rz] = part.rotation || [0, 0, 0];
	if (rx === 0 && ry === 0 && rz === 0) {
		return `PartPose.offset(${offset.map(f).join(', ')})`;
	}
	return `PartPose.offsetAndRotation(${offset.map(f).join(', ')}, ` +
		`${rad(-rx)}, ${rad(-ry)}, ${rad(rz)})`;
}

function cubeListBuilder(cubes, origin, indent) {
	if (!cubes.length) return 'CubeListBuilder.create()';

	const pad = '\t'.repeat(indent);
	const lines = cubes.map(cube => {
		const [x, y, z] = cubeOffset(cube, origin);
		return `${pad}.texOffs(${cube.uv[0]}, ${cube.uv[1]})` +
			`.addBox(${f(x)}, ${f(y)}, ${f(z)}, ` +
			`${f(cube.size[0])}, ${f(cube.size[1])}, ${f(cube.size[2])}, ` +
			`new CubeDeformation(${f(cube.inflate || 0)}))`;
	});

	return `CubeListBuilder.create()\n${lines.join('\n')}`;
}

// segments emitted with a zeroed pose, PartPose.offset(0,24,0), the flipped-Y identity, because MarionetteModel.setupAnim calls setPos on every segment every frame so whatever pose the file carries is dead on arrival emitting the real origin would only mislead
// again later we might want to replace this which would make the undoing of the +24 y in MarionetteModel unnecessary
function emitPart(part, parentVar, parentOrigin, out) {
	const isRoot = parentVar === 'partdefinition';
	const pose = isRoot
		? 'PartPose.offset(0.0F, 24.0F, 0.0F)'
		: childPose(part, parentOrigin);

	out.push(
		`\t\tPartDefinition ${part.var} = ${parentVar}.addOrReplaceChild("${part.name}", ` +
		`${cubeListBuilder(part.cubes, part.origin, 4)}, ${pose});`
	);

	for (const child of part.children) {
		out.push('');
		emitPart(child, part.var, part.origin, out);
	}
}

export function emitModel(rig, names) {
	const body = [];
	for (const segment of rig.segments) {
		emitPart(segment.part, 'partdefinition', null, body);
		body.push('');
	}

	const segmentNames = rig.segments.map(s => `"${s.part.name}"`);

	return `package ${names.package};

import net.jelly.marionette_lib.utility.MarionetteModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;

/**
 * Generated by the Marionette Blockbench plugin. Regenerating overwrites this
 * file -- keep hand edits somewhere else.
 *
 * Segment names below are in chain order and are index-aligned with
 * ${names.className}Entity's part list. Reordering one without the other will
 * silently pair the wrong model part with the wrong segment.
 */
public class ${names.className}Model extends MarionetteModel<${names.className}Entity> {

	public static LayerDefinition createBodyLayer() {
		MeshDefinition meshdefinition = new MeshDefinition();
		PartDefinition partdefinition = meshdefinition.getRoot();

${body.join('\n')}
		return LayerDefinition.create(meshdefinition, ${rig.textureWidth}, ${rig.textureHeight});
	}

	public ${names.className}Model(ModelPart root) {
		super(root, new String[] {
${wrapNames(segmentNames)}
		});
	}
}
`.replace(/\t/g, '    ');
}

function wrapNames(names) {
	const lines = [];
	let current = '\t\t\t';

	for (let i = 0; i < names.length; i++) {
		const piece = names[i] + (i === names.length - 1 ? '' : ',');
		if (current.trim() && (current + ' ' + piece).length > 96) {
			lines.push(current);
			current = '\t\t\t';
		}
		current += (current.trim() ? ' ' : '') + piece;
	}
	if (current.trim()) lines.push(current);
	return lines.join('\n');
}

// segments(count, sizeXZ, sizeY, length) takes blocks not model units, FabrikAnimator works in world space and MarionetteModel is the only thing that multiplies by 16
// runs of segments sharing dimensions collapse into one segments(...) call
// sizeXZ/sizeY are hitbox dimensions with no representation in blockbench, vaguely guessed from each segment's geometry bounding box
export function emitEntity(rig, names) {
	const limbFields = rig.limbs.map(limb =>
		`\tprivate final Limb<MarionettePart<${names.className}Entity>> ${limb.var};`
	);

	const limbBuilders = rig.limbs.map(limb => {
		const calls = runsOf(limb.segments).map(run =>
			run.count === 1
				? `\t\t\t\t.segment(${f(run.sizeXZ)}, ${f(run.sizeY)}, ${f(run.lengthBlocks)})`
				: `\t\t\t\t.segments(${run.count}, ${f(run.sizeXZ)}, ${f(run.sizeY)}, ${f(run.lengthBlocks)})`
		);
		if (limb.primeDirection) {
			const [x, y, z] = limb.primeDirection;
			calls.push(`\t\t\t\t.bodyPrimeDirection(new Vec3(${d(x)}, ${d(y)}, ${d(z)}))`);
		}
		if (limb.attachment) {
			const { limb: parent, partIndex, offset } = limb.attachment;
			calls.push(`\t\t\t\t.attachRoot(${parent}.parts()[${partIndex}], ` +
				`new Vec3(${d(offset[0])}, ${d(offset[1])}, ${d(offset[2])}))`);
		}
		return `\t\t${limb.var} = Limb.builder(this)\n${calls.join('\n')}\n\t\t\t\t.build();`;
	});

	const limbList = rig.limbs.map(limb => limb.var).join(', ');

	return `package ${names.package};

import net.jelly.marionette_lib.utility.Limb;
import net.jelly.marionette_lib.utility.Marionette;
import net.jelly.marionette_lib.utility.MarionettePart;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.${names.baseClassImport};
import net.minecraft.world.level.Level;${rig.limbs.some(limb => limb.primeDirection || limb.attachment) ? '\nimport net.minecraft.world.phys.Vec3;' : ''}
import net.minecraftforge.entity.PartEntity;

import java.util.List;

/**
 * Generated by the Marionette Blockbench plugin. Regenerating overwrites this
 * file. Keep hand edits elsewhere.
 *
 * The segment dimensions below came from the Blockbench geometry:
 * {@code length} is the bone length in blocks and is exact; {@code sizeXZ} and
 * {@code sizeY} are hitbox sizes guessed from each segment's bounding box, which
 * will likely require tuning.
 *
 * Limb order defines part order, which ${names.className}Model's segment
 * name array must match.
 */
public class ${names.className}Entity extends ${names.baseClass} implements Marionette {

${limbFields.join('\n')}

	public ${names.className}Entity(EntityType<? extends ${names.baseClass}> entityType, Level level) {
		super(entityType, level);
${limbBuilders.join('\n\n')}
	}

	@Override
	public List<Limb<?>> getLimbs() {
		return List.of(${limbList});
	}

	@Override
	public boolean isMultipartEntity() {
		return true;
	}

	@Override
	public PartEntity<?>[] getParts() {
		return getMarionetteParts();
	}

	@Override
	public void remove(RemovalReason removalReason) {
		super.remove(removalReason);
		removeMarionette(removalReason);
	}

	@Override
	public void tick() {
		super.tick();

		// Aim each limb before solving, e.g.
		//     ${rig.limbs[0] ? rig.limbs[0].var : 'limb'}.animator().setFabrikTarget(someWorldPosition);

		tickMarionette();
	}
}
`.replace(/\t/g, '    ');
}

export function runsOf(segments) {
	const runs = [];
	for (const segment of segments) {
		const last = runs[runs.length - 1];
		if (
			last &&
			last.sizeXZ === segment.sizeXZ &&
			last.sizeY === segment.sizeY &&
			last.lengthBlocks === segment.lengthBlocks
		) {
			last.count++;
		} else {
			runs.push({
				count: 1,
				sizeXZ: segment.sizeXZ,
				sizeY: segment.sizeY,
				lengthBlocks: segment.lengthBlocks,
			});
		}
	}
	return runs;
}

export function emitRenderer(rig, names) {
	return `package ${names.package};

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.math.Axis;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.renderer.culling.Frustum;
import net.minecraft.client.renderer.entity.EntityRendererProvider;
import net.minecraft.client.renderer.entity.MobRenderer;
import net.minecraft.resources.ResourceLocation;

/**
 * Generated by the Marionette Blockbench plugin. Regenerating overwrites this
 * file. Keep hand edits elsewhere.
 *
 * Like a vanilla modded entity, wo registrations are still yours to make:
 *
 *   EntityRenderersEvent.RegisterLayerDefinitions:
 *       event.registerLayerDefinition(${names.className}Renderer.${names.layerConstant}, ${names.className}Model::createBodyLayer);
 *
 *   EntityRenderersEvent.RegisterRenderers:
 *       event.registerEntityRenderer(ModEntities.${names.screamingName}.get(), ${names.className}Renderer::new);
 */
public class ${names.className}Renderer extends MobRenderer<${names.className}Entity, ${names.className}Model> {

	private static final ResourceLocation TEXTURE =
			new ResourceLocation("${names.modid}:textures/entity/${names.textureName}.png");

	public static final ModelLayerLocation ${names.layerConstant} = new ModelLayerLocation(
			new ResourceLocation("${names.modid}", "${names.layerName}"), "main");

	public ${names.className}Renderer(EntityRendererProvider.Context context) {
		super(context, new ${names.className}Model(context.bakeLayer(${names.layerConstant})), ${f(rig.shadowRadius)});
	}

	@Override
	protected void setupRotations(${names.className}Entity entity, PoseStack poseStack, float ageInTicks, float rotationYaw, float partialTicks) {
		poseStack.mulPose(Axis.YP.rotationDegrees(180));
	}

	@Override
	public boolean shouldRender(${names.className}Entity entity, Frustum camera, double x, double y, double z) {
		if (super.shouldRender(entity, camera, x, y, z)) return true;
		return camera.isVisible(entity.getMarionetteBoundingBoxForCulling(entity));
	}

	@Override
	public ResourceLocation getTextureLocation(${names.className}Entity entity) {
		return TEXTURE;
	}
}
`.replace(/\t/g, '    ');
}

// sidecar is currently vestigial but is exported for a couple reasons:
// proper debugging and reference for a proper export
// in the future, optimally rigs are handled at runtime and this will be the only necessary file outside the Model.java.
export function emitSidecar(rig, names) {
	return JSON.stringify({
		format: 'marionette-rig',
		format_version: 1,
		generator: names.generator,
		class_name: names.className,
		package: names.package,
		texture: { width: rig.textureWidth, height: rig.textureHeight },
		units_per_block: 16,
		limbs: rig.limbs.map(limb => ({
			name: limb.name,
			field: limb.var,
			prime_direction: limb.primeDirection,
			prime_direction_space: limb.primeDirection ? 'body' : null,
			attachment: limb.attachment && {
				limb: limb.attachment.limb,
				part_name: limb.attachment.partName,
				part_index: limb.attachment.partIndex,
				offset: limb.attachment.offset,
			},
			segments: limb.segments.map(segment => ({
				part_name: segment.part.name,
				length_units: segment.lengthUnits,
				length_blocks: segment.lengthBlocks,
				size_xz: segment.sizeXZ,
				size_y: segment.sizeY,
				size_source: segment.hasGeometry ? 'geometry_bounds' : 'default',
			})),
		})),
		part_order: rig.segments.map(s => s.part.name),
	}, null, '\t') + '\n';
}
